apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ../../../monitoring/k8s/prometheus.yaml
  - ../../../monitoring/k8s/otel-collector.yaml
  - ../../../monitoring/k8s/grafana.yaml
