apiVersion: v1
kind: Service
metadata:
  name: zhushou
  labels:
    app: zhushou
spec:
  type: ClusterIP
  selector:
    app: zhushou
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
