#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_NAME="${ASSISTANT_INSTALL_E2E_IMAGE:-assistant-install-e2e:local}"
INSTALL_URL="${ASSISTANT_INSTALL_URL:-https://assistant.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
ASSISTANT_E2E_MODELS="${ASSISTANT_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e ASSISTANT_INSTALL_URL="$INSTALL_URL" \
  -e ASSISTANT_INSTALL_TAG="${ASSISTANT_INSTALL_TAG:-latest}" \
  -e ASSISTANT_E2E_MODELS="$ASSISTANT_E2E_MODELS" \
  -e ASSISTANT_INSTALL_E2E_PREVIOUS="${ASSISTANT_INSTALL_E2E_PREVIOUS:-}" \
  -e ASSISTANT_INSTALL_E2E_SKIP_PREVIOUS="${ASSISTANT_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e ASSISTANT_NO_ONBOARD=1 \
  -e OPENAI_API_KEY="$OPENAI_API_KEY" \
  -e ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
  -e ANTHROPIC_API_TOKEN="$ANTHROPIC_API_TOKEN" \
  "$IMAGE_NAME"
