export const browserCoreExamples = [
  "zhushou browser status",
  "zhushou browser start",
  "zhushou browser stop",
  "zhushou browser tabs",
  "zhushou browser open https://example.com",
  "zhushou browser focus abcd1234",
  "zhushou browser close abcd1234",
  "zhushou browser screenshot",
  "zhushou browser screenshot --full-page",
  "zhushou browser screenshot --ref 12",
  "zhushou browser snapshot",
  "zhushou browser snapshot --format aria --limit 200",
  "zhushou browser snapshot --efficient",
  "zhushou browser snapshot --labels",
];

export const browserActionExamples = [
  "zhushou browser navigate https://example.com",
  "zhushou browser resize 1280 720",
  "zhushou browser click 12 --double",
  'zhushou browser type 23 "hello" --submit',
  "zhushou browser press Enter",
  "zhushou browser hover 44",
  "zhushou browser drag 10 11",
  "zhushou browser select 9 OptionA OptionB",
  "zhushou browser upload /tmp/zhushou/uploads/file.pdf",
  'zhushou browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "zhushou browser dialog --accept",
  'zhushou browser wait --text "Done"',
  "zhushou browser evaluate --fn '(el) => el.textContent' --ref 7",
  "zhushou browser console --level error",
  "zhushou browser pdf",
];
